// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCvrhQ0G5A6Ne1cId4AAgZbRjm4446s_M',
    appId: '1:640336094597:web:bc996c1cfa157d85ced0ec',
    messagingSenderId: '640336094597',
    projectId: 'chat-app-27b8d',
    authDomain: 'chat-app-27b8d.firebaseapp.com',
    storageBucket: 'chat-app-27b8d.appspot.com',
    measurementId: 'G-9L9SL5G7MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLsYdj2bL0T_Nfy-sp5odiE2Bi87TfErQ',
    appId: '1:640336094597:android:2fc1297d1824a10aced0ec',
    messagingSenderId: '640336094597',
    projectId: 'chat-app-27b8d',
    storageBucket: 'chat-app-27b8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCA7SnsezfvlNPqlcreIFwr3cxb2APvA0',
    appId: '1:640336094597:ios:a344099a61553acbced0ec',
    messagingSenderId: '640336094597',
    projectId: 'chat-app-27b8d',
    storageBucket: 'chat-app-27b8d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCA7SnsezfvlNPqlcreIFwr3cxb2APvA0',
    appId: '1:640336094597:ios:77fa7c15bf946280ced0ec',
    messagingSenderId: '640336094597',
    projectId: 'chat-app-27b8d',
    storageBucket: 'chat-app-27b8d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
